src/FlagX0.Web/Models/ErrorViewModel.cs
namespace FlagX0.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/FlagX0.Web/Models/FlagIndexViewModel.cs
using FlagX0.Web.DTOs;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FlagX0.Web.Models
{
    public class FlagIndexViewModel
    {
        public List<FlagDto> Flags { get; set; }
    }
}

src/FlagX0.Web/Models/FlagViewModel.cs
namespace FlagX0.Web.Models
{
    public class FlagViewModel
    {
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
    }
}

src/FlagX0.Web/Controllers/FlagsController.cs
using FlagX0.Web.Business.UseCases;
using FlagX0.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FlagX0.Web.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class FlagsController : Controller
    {
        private readonly AddFlagUseCase _addFlagUseCase;
        private readonly GetFlagsUseCase _getFlagsUseCase;

        public FlagsController(AddFlagUseCase addFlagUseCase, GetFlagsUseCase getFlagsUseCase)
        {
            _addFlagUseCase = addFlagUseCase;
            _getFlagsUseCase = getFlagsUseCase;
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return View(new FlagViewModel());
        }

        [HttpPost("create")]
        public async Task <IActionResult> AddFlagToDatabase(FlagViewModel request)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool isCreated = await _addFlagUseCase.Execute(request.Name, request.IsEnabled);

            return RedirectToAction("Index");
        }
        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            var listFlags = await _getFlagsUseCase.Execute();

            return View(new FlagIndexViewModel()
            {
                Flags = listFlags
            });
        }
    }
}

src/FlagX0.Web/Controllers/HomeController.cs
using System.Diagnostics;
using FlagX0.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace FlagX0.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/FlagX0.Web/Views/Flag/CreateFlag.cshtml
@model FlagViewModel

<form asp-action="create" asp-controller="flags" method="post" class="row row-cols-lg-auto g-3 align-items-center">

    <div class="col-12">
        <label class="visually-hidden" for="flagName">
            Flag Name
        </label>
        <div class="input-group">
            <div class="input-group-text">Flag Name</div>
            <input type="text" asp-for="Name" class="form-control" id="inlineFormInputGroupUsername" placeholder="Flag Name" />
        </div>
    </div>
    <div class="col-12">
        <div class="form-check form-switch">
            <input class="form-check-input" asp-for="IsEnabled" type="checkbox" role="switch" />
        </div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">
            Create flag
        </button>
    </div>
</form>

src/FlagX0.Web/Views/Flags/Create.cshtml
@model FlagViewModel

<form asp-action="create" asp-controller="flags" method="post" class="row row-cols-lg-auto g-3 align-items-center">

    <div class="col-12">
        <label class="visually-hidden" for="flagName">
            Flag Name
        </label>
        <div class="input-group">
            <div class="input-group-text">Flag Name</div>
            <input type="text" asp-for="Name" class="form-control" id="inlineFormInputGroupUsername" placeholder="Flag Name" />
        </div>
    </div>
    <div class="col-12">
        <div class="form-check form-switch">
            <input class="form-check-input" asp-for="IsEnabled" type="checkbox" role="switch" />
        </div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">
            Create flag
        </button>
    </div>
</form>

src/FlagX0.Web/Views/Flags/Index.cshtml
@model FlagIndexViewModel

<a asp-action="create" asp-controller="flags" class="btn btn-primary">Create Flag</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Flag Name</th>
            <th scope="col">Active</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var flag in Model.Flags)
        {
            <tr>
                <th scope="row">@flag.Name</th>
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" readonly asp-for="@flag.IsEnabled" type="checkbox" role="switch" />
                    </div>
                </td>
                <td>
                    <button type="button" class="btn btn-outline-danger">
                        <i class="bi bi-archive"></i>
                    </button>
                    <button type="button" class="btn btn-outline-primary">
                        <i class="bi bi-pencil"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

src/FlagX0.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if(User.Identity?.IsAuthenticated ?? false)
{
    <a asp-action="create" asp-controller="flags" class="btn btn-primary">Create Flag</a>
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/FlagX0.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlagX0.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlagX0.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlagX0.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flags" asp-action="Index">Flags</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - FlagX0.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>